### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by chmdznr** [Athlon1600/php-proxy#1]
Hello,
Is there any particular configuration for php-proxy script?
I'm installing it on my dedicated server and it doesn't work for facebook.com saying that the cookie isn't enabled. I suspect that's something to do with cookie handling on the script.

Btw:
somebody that want to install the script should be aware that the templates is using php short-tag. I need to change it to php long tag to make it work.

**Comment by Athlon1600** [comment]
>  Is there any particular configuration for php-proxy script?

Whatever is in config.php that's it.

I'm not finished with CookiePlugin so I wouldn't expect any session stuff to work right now. Give it a week or two for me to finish everything that still needs work.
