### ISSUE TITLE
plugin tutorial/help/cheat sheet

### ISSUE THREAD

**Issue by Clevero** [Athlon1600/php-proxy#10]
i would like to add new sites for my wonts.

but from the youtube code i didn't know how to exactly implement new sites

do you have any help?

**Comment by Athlon1600** [comment]
What is a "wont"?

**Comment by Clevero** [comment]
sorry for my bad english skills. i'm not a native speaker in that language :/

with my "wonts", i mean the things i usally do. other words for that in englisch (dict.cc) are "habits" or "usualness". in german so called "Gewohnheit" :)

**Comment by Athlon1600** [comment]
What sites would you like to implement?

**Comment by reinerotto** [comment]
g+, facebook, twitter, please.

**Comment by Clevero** [comment]
sites like ARD or ZDF Mediathek. Those sites are blocked in my school network and have have good documentations.

http://www.ardmediathek.de/tv
http://www.zdf.de/ZDFmediathek#
