### ISSUE TITLE
Name collision with laravel

### ISSUE THREAD

**Issue by martin-sanjuan** [Athlon1600/php-proxy#100]
PHP Fatal error:  Cannot redeclare starts_with() (previously declared in /home/msanjuan/Documents/dtv/helium/src/api/vendor/illuminate/support/helpers.php:745) in /home/msanjuan/Documents/dtv/helium/src/api/vendor/athlon1600/php-proxy/src/helpers.php on line 18

**Comment by Athlon1600** [comment]
okay it should be working now. Just update to the latest version:
https://github.com/Athlon1600/php-proxy/commit/0f501a324e9935d97989411355e84a09d1a2712b

**Comment by martin-sanjuan** [comment]
Thanks!
