### ISSUE TITLE
literotica.com

### ISSUE THREAD

**Issue by tibbie123** [Athlon1600/php-proxy#101]
Hi, when visitors go to literotica.com and click on stories and pics they see ��=�r۸��g��S{�T�����؞r�8Im.��3��IHdL������������n�"u�#R�l�bI$�h4�ݍp��C��HU   etc

This is on v5.1.1 and v5.0.5

**Comment by Athlon1600** [comment]
seems to work fine for me? Which pages on that site return those characters?

**Comment by tibbie123** [comment]
Hi, sorry should have given you an url - https://www.literotica.com/stories/
that is what I see on unblockvideos.com as well.
thanks!

**Comment by Athlon1600** [comment]
Hey, go to your php-proxy-app's config.php and change your curl options to this:

```php
// additional curl options to go with each request
$config['curl'] = array(
	CURLOPT_ENCODING => 'gzip'
	// CURLOPT_PROXY => '',
	// CURLOPT_CONNECTTIMEOUT => 5
);
```

**Comment by tibbie123** [comment]
Brilliant thanks!!!!!
