### ISSUE TITLE
gats.io

### ISSUE THREAD

**Issue by tibbie123** [Athlon1600/php-proxy#107]
Hi, have had a few requests for this site so can be logged into and used on our proxies. Per alexa https://www.alexa.com/siteinfo/gats.io it is a BIG site.

thanks

**Comment by Athlon1600** [comment]
Too much scripting on that site. No web proxy will ever work perfectly with JavaScript heavy sites. For this, you should just use an actual HTTP proxy:  
https://www.proxynova.com/proxy-software/

**Comment by tibbie123** [comment]
Not a problem, appreciated.
