### ISSUE TITLE
YouTube mobile version blank

### ISSUE THREAD

**Issue by TheMetaPirate** [Athlon1600/php-proxy#11]
We already had the same error once back :)

I updated my page with your proxy and realized that It stoped working (YouTube): http://i.imgur.com/AOP3zBM.jpg

**Comment by Athlon1600** [comment]
decrypting all that javascript inside m.youtube.com is impossible right now. Why use mobile in the first place? You're better off using an actual server here instead: http://www.proxynova.com/proxy.pac

**Comment by TheMetaPirate** [comment]
We at highschool,work with iPads, everything from IP proxys to VPNs are blocked, were not able to install apps. 

VPNs don't connect ports are blocked
IP proxys (I did test yours just are stuck loading)

I can wait, and others too
