### ISSUE TITLE
How to modify the player?

### ISSUE THREAD

**Issue by caststrpos** [Athlon1600/php-proxy#114]
How do we modify the player? Specifically, I want to remove the download button from the youtube, pornhub, etc

**Comment by Athlon1600** [comment]
The player itself does not have a download button? Post a screenshot of what you are seeing.

**Comment by caststrpos** [comment]
![image](https://user-images.githubusercontent.com/37906357/38178838-da8dc272-35cf-11e8-8659-896eaf88c900.png)

The download button on the far right.

**Comment by Athlon1600** [comment]
oh that player is generated by the web-browser, there is nothing we can do on our end to change how the video player looks like or what buttons it has.

**Comment by ash121121** [comment]
you could use my proxy stripper plugin and remove it
