### ISSUE TITLE
php-proxy is not loading site completey

### ISSUE THREAD

**Issue by mubbashar** [Athlon1600/php-proxy#13]
I have download your plugin. And configure it on my localhost and on live server as well. but when i try to visit a page url. It trim the page from the end

on your demo site it is loading fine
https://kc.unblockvideos.com/index.php?q=aHR0cDovL21wai1leHByZXNzLm9yZy9wYXBlcnMuaHRtbA

but when i load the same on my server. the html go trim 

![image](https://cloud.githubusercontent.com/assets/378379/6500921/d3a74f4e-c333-11e4-9098-c82747733c6b.png)

i try to debug and found something

in index.php on line 74

you are calling this method $response = $proxy->execute($request);
and i print the response. and all html was there

so after calling $response->sendHeaders(); on line 80
you called $output = $response->getContent(); on line 83
the html got trim. not sure why

can you help me with this.
thanks!

**Comment by Athlon1600** [comment]
Send me a link to your server where php-proxy is installed.
