### ISSUE TITLE
Does not generate preview on Facebook

### ISSUE THREAD

**Issue by jmar83** [Athlon1600/php-proxy#145]
As title says...

Why that issue??

**Comment by jayjupdhig** [comment]
same question here...

**Comment by jmar83** [comment]
-> Question is still pendent, but maby it's too complex to find a solution for that issue here?

Thank you very much in advance for your feedbacks.

With kind regards,
Jan

**Comment by jmar83** [comment]
-> https://github.com/Athlon1600/php-proxy-app/issues/199

**Comment by jmar83** [comment]
Problem solved by not-using your shitware...

**Comment by jmar83** [comment]
-> https://www.php.de/forum/webentwicklung/php-einsteiger/1587913-warum-kann-dieses-reverse-proxy-php-skript-keine-vorschau-bei-fb-posts-generieren

**Comment by jmar83** [comment]
So don't use it - never ever: https://www.php.de/forum/webentwicklung/php-einsteiger/1587913-warum-kann-dieses-reverse-proxy-php-skript-keine-vorschau-bei-fb-posts-generieren/page2

With kind regards,
Jan

**Comment by jmar83** [comment]
...
