### ISSUE TITLE
TAKE CARE (!!!), that script is VERY VERY DANGEROUS!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by jmar83** [Athlon1600/php-proxy#147]
So don't use it - never ever: https://www.php.de/forum/webentwicklung/php-einsteiger/1587913-warum-kann-dieses-reverse-proxy-php-skript-keine-vorschau-bei-fb-posts-generieren/page2

With kind regards,
Jan

**Comment by jmar83** [comment]
WTF why no answer??!

**Comment by TheRealZagon** [comment]
Because what you are saying makes no sense...

**Comment by jmar83** [comment]
...
