### ISSUE TITLE
Strange 403 Forbidden error

### ISSUE THREAD

**Issue by Aganel** [Athlon1600/php-proxy#15]
Hello!
I downloaded your script from php-proxy.com and installed it to localhost. It works OK.
But when i upload it to shared hosting, it doesn't work.
host/ and host/index.php is opening successfully. But after entering any address and pressing the button i see an error "You don't have permission to access /index.php on this server."
Just for test I tried to run index.php with q=1 parameter, it loads the page (with errors about undefined host and scheme, of course).
I am confused what could be the problem here.

**Comment by TheMetaPirate** [comment]
I'm not the author of the proxy but, do you have php5-curl installed in your server?

**Comment by Athlon1600** [comment]
send me a link to your site

**Comment by Aganel** [comment]
Athlon1600, I e-mailed it to you.
