### ISSUE TITLE
Upstream proxy support (CURLOPT_PROXY)

### ISSUE THREAD

**Issue by dimzon** [Athlon1600/php-proxy#16]
Please add to configuration CURLOPT_PROXY support.

Explanation:
I have i2p && tor onto my VPS
I have configured privoxy to route *.onion to tor and to route *.i2p to i2p 
Now I just set CURLOPT_PROXY=>'127.0.01:8118' and got perfect online proxy with tor/i2p support

**Comment by Athlon1600** [comment]
yup probably would be a good idea now to just add a config['curl'] = array(...)  option so anyone could just add whatever additional curl options they want. Added here:
https://github.com/Athlon1600/php-proxy/commit/7c072e
