### ISSUE TITLE
Gmail cookies problem

### ISSUE THREAD

**Issue by AoiRei** [Athlon1600/php-proxy#19]
I have a default installation of php-proxy, which includes "Cookies" plugin, but when i try to login to gmail then i get "Oops! Your browser seems to have cookies disabled. Make sure cookies are enabled or try opening a new browser window."

Is there a way to fix it?

Thanx

**Comment by domsie** [comment]
... have the same issue @facebook.com...
any fix available?

**Comment by Athlon1600** [comment]
Gmail and facebook are too complicated to deal with cookies properly at this  time.
