### ISSUE TITLE
issue to play youtube video

### ISSUE THREAD

**Issue by talibnaik** [Athlon1600/php-proxy#20]
there is issue to play new links of youtube. please check example

https://www.youtube.com/watch?v=ijLZ9-rlEhg

this is not working in your proxy... can you please fix this..

**Comment by Clevero** [comment]
i can't play this video on my instance (*** you to GEMA) yet. but i can watch german videos as normal.

what do you mean with "new" links? could you watch any kind of videos on youtube befor this change?
if not, can you please give us some informations about your system running the proxy? (installed requirements, version of php-proxy etc.)

**Comment by talibnaik** [comment]
yes i just install and check everything running their just some link not working.. 
it is my my proxy just update..
http://videos.megashare.mx/proxy2/

and my mean to new link is the links which have - in its id as:
https://www.youtube.com/watch?v=ijLZ9-rlEhg

**Comment by talibnaik** [comment]
any update... have you plan to fix this?

**Comment by Clevero** [comment]
i'm not a developer of this project that time. but i hope ich will be it soon (first add some website i wonna use in school).

my first thinking was that, maybe the video is too long and your server can't handle this (?). but i'm not sure

@Athlon1600 have you any ideas why there is this problem with this specific video?

**Comment by Athlon1600** [comment]
it's not just this specific video, YouTube uses special encoding on their video URLs that have ads. Look at the youtube plugin:
https://github.com/Athlon1600/php-proxy/blob/master/plugins/YoutubePlugin.php

previous sig_decipher was based off of:
...html5player-en_US-**vfl20EdcH**/html5player.js

and right now YouTube is using:
html5player-en_US-**vfl1r59NI**/html5player.js

a different sig_decipher has to be written once again. A proxy script that auto-updates itself with all the plugins is what I'm working on right now and I'll probably have something done by next week
