### ISSUE TITLE
Install in Laravel 5.2 encountered a bug 

### ISSUE THREAD

**Issue by cynhard** [Athlon1600/php-proxy#25]
This is the information.
`Problem 1
    - Conclusion: remove symfony/event-dispatcher v3.0.4
    - Conclusion: don't install symfony/event-dispatcher v2.8.4
    - Installation request for athlon1600/php-proxy ^3.0 -> satisfiable by athlon1600/php-proxy[3.0.0].
    - Conclusion: don't install symfony/event-dispatcher v3.0.4
    - athlon1600/php-proxy 3.0.0 requires symfony/event-dispatcher ~2.6 -> satisfiable by symfony/event-dispatcher[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.10, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.11, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.12, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.13, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.7, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.8, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.9, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.0, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.1, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.10, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.11, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.2, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.3, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.4, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.5, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.6, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.7, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.8, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.7.9, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.8.0, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.8.1, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.8.2, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.8.3, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.0, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.1, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.2, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.3, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.4, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.5, v3.0.4].
    - Can only install one of: symfony/event-dispatcher[v2.6.6, v3.0.4].
    - Installation request for symfony/event-dispatcher == 3.0.4.0 -> satisfiable by symfony/event-dispatcher[v3.0.4].`

**Comment by arydeoblo** [comment]
Seem symfony/event-dispacther need to be upgrade latest version, same error encounter in yii2.

**Comment by Toilal** [comment]
Same with symfony 3

**Comment by Toilal** [comment]
There's a breaking change to upgrade to event-dispatcher 3.x

See migration from some other projects : 
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1829/files
https://github.com/cpliakas/git-wrapper/pull/110/files

Basically, `$event->getName()` and `$event->getDispatcher()` have been removed. Those properties are now available as the second and third argument of the callback function.

I'll open a pull request to support both event-dispatcher 2.x && 3.x.

**Comment by Toilal** [comment]
It's possible to test the Pull Request with ```composer require athlon1600/php-proxy:dev-master```.

You have to set my repository in composer.json

```json
    ...
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Toilal/php-proxy"
        }
    ],
    ...
```
