### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by Karlingue** [Athlon1600/php-proxy#3]
Hello

I have try you're proxy, but doesn't work ^^

http://loopze.alwaysdata.net/

**Comment by Athlon1600** [comment]
The proxy you have installed on that page is Glype and not PHP-Proxy...

**Comment by Karlingue** [comment]
yes because you're proxy doesn't work :) sorry

**Comment by Athlon1600** [comment]
well what does it say? Do you just get a white screen?

**Comment by Karlingue** [comment]
Sorry, hop : http://loopze.alwaysdata.net/php-proxy/

you can try

**Comment by Karlingue** [comment]
Sorry, hop : http://pourraty.alwaysdata.net/php-proxy/

you can try

**Comment by Karlingue** [comment]
Sorry, hop : http://kazoine.alwaysdata.net/php-proxy/

you can try

**Comment by Athlon1600** [comment]
seems to work for me...
http://i.imgur.com/XOgCU0l.png?1

Which part is not working for you?

**Comment by Karlingue** [comment]
Try with : http://www.openclassrooms.com/

**Comment by Athlon1600** [comment]
Is it possible that you're using an outdated php-proxy script? I just installed the latest version here:
https://www.php-proxy.com/test/php-proxy/

and http://www.openclassrooms.com/ works fine

**Comment by Karlingue** [comment]
:s how to debug so ? :(

**Comment by Athlon1600** [comment]
I don't understand your question?
