### ISSUE TITLE
How do I...

### ISSUE THREAD

**Issue by rydens** [Athlon1600/php-proxy#35]
So, I've installed it. Sorry, not too familiar with composer; how do I run it or such to use it?

Thanks,

> rydens

**Comment by Athlon1600** [comment]
Run what? php-proxy or composer?

**Comment by rydens** [comment]
php-proxy

**Comment by Athlon1600** [comment]
it's all explained on the main page:  
https://github.com/Athlon1600/php-proxy  
  
Are you sure you're looking for php-proxy and not **php-proxy-app**? Only one of those is "runnable".

**Comment by rydens** [comment]
How do I use php-proxy-app?
