### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by hqin2013** [Athlon1600/php-proxy#4]
hi,thank you for your great script.

I found 2 issues:
1. when i use composer install online,it fails.but with zip package,it's ok.
2. the proxied page seems not confortable :),i use php5.3.9
![default](https://cloud.githubusercontent.com/assets/3657122/5951699/7bf488d8-a7a5-11e4-8c82-3724e6228af9.JPG)

Regards

**Comment by Athlon1600** [comment]
Fixed
