### ISSUE TITLE
Proxified web page contains strange characters

### ISSUE THREAD

**Issue by webaddicto** [Athlon1600/php-proxy#49]
I typed this URL in unblockvideos.com:

`http://mangafox.me/manga/bleach/vTBD/c686/1.html`

And it generates a web page with strange characters, see the screenshot:

![strange-chars](https://cloud.githubusercontent.com/assets/8770136/22949260/efa628f0-f301-11e6-97d7-58a42b73b043.png)

Here are the headers:

```
                    [headers] => Proxy\Http\ParamStore Object
                        (
                            [data:protected] => Array
                                (
                                    [content-type] => text/html; charset=utf-8
                                    [content-disposition] => filename="1.html"
                                    [cache-control] => no-cache, no-store, must-revalidate
                                    [pragma] => no-cache
                                    [expires] => 0
                                )
```

With Glype it works fine:

![glype](https://cloud.githubusercontent.com/assets/8770136/22949284/fd498628-f301-11e6-9d46-1ee6f5e87265.png)

**Comment by webaddicto** [comment]
@Athlon1600

Any update on this behavior? Could you reproduce it?

Just tested with unblockvideos and with latest php-proxy, the issue is still present.

![issue1](https://user-images.githubusercontent.com/8770136/33528603-cb680498-d863-11e7-8839-08a0b3a97602.png)

**Comment by Athlon1600** [comment]
People at mangafox.me must have changed something on their server, because the site appears to be working now:  
https://unblockvideos.com/#url=http://mangafox.me/manga/bleach/vTBD/c686/1.html
