### ISSUE TITLE
request for more detailed requirements/installation instructions

### ISSUE THREAD

**Issue by bennetthaselton** [Athlon1600/php-proxy#5]
Is it easy to list the prerequisites and requirements that are necessary before you can install PHP-Proxy just by a plain upload of all of the PHP files?  (And maybe add this to the Readme in a future release.)

I have a host with CentOS 5.8 which comes with PHP 5.1.6 pre-installed.  I assume PHP-Proxy requires at least PHP 5.3 because of the "use" lines?  But actually if PHP-Proxy uses Symfony, then according to this page:
http://symfony.com/doc/current/book/installation.html
Symfony requires PHP 5.4 or higher, so I need PHP 5.4?

And do I need to install Symfony as well?  The page at
http://symfony.com/doc/current/book/installation.html
actually gives instructions for "installing the Symfony installer", but I assume that's not all that's necessary in order for lines like
use Symfony\Component\HttpFoundation\Request;
to work correctly.  What else would I have to do to my system in order to add the support that PHP-Proxy needs?

Have you installed it on CentOS 5.x at all?  Would it be easier just to get a CentOS 6 box?

**Comment by TheMetaPirate** [comment]
First of all, (i didn't make the proxy), you don't need Symfony, but you NEED cURL.

Symfony is used to make an instalation faster.

Running the proxy on a Raspberry Pi B+ didn't need it, I installed it after reading the manual that I didn't lol.

You just need FTP access to the server and paste the zip. that should be it

**Comment by bennetthaselton** [comment]
Well like I said in the original message, I know you need at least PHP 
5.3, which doesn't come with CentOS 5.x, so it's not always just as 
simple as uploading the files in the zip :)  Maybe you never have to 
deal with machines any more that have CentOS 5.x on them any more, but I 
still do...

Are you absolutely sure that you don't need Symfony installed? Because 
these lines appear right at the top of index.php:

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ParameterBag;

Hoping that the author can weigh in as well?

Bennett

**Comment by TheMetaPirate** [comment]
What can I say, you don't lose anything by trying.

**Comment by Athlon1600** [comment]
Symfony is already included in /vendor/symfony if you're downloading a pre-installed version from php-proxy.com. If you're installing this through composer then symfony will be installed automatically.

**Comment by bennetthaselton** [comment]
Thanks.  While I'll wait a while for the full documentation, can you tell me if there are any other system requirements that you know of off the top of your head, other than PHP 5.3 or greater?  Do I also need CentOS 6?  At least, can you tell me what type of system you're running it on -- e.g. CentOS 6 with PHP 5.3?  (So even if you don't know what's strictly *required* (which can actually be hard to figure out), at least you can give me the specs for at least one system where you know it works :) )

**Comment by Athlon1600** [comment]
Operating system has nothing to do with this. If you're able to install whatever PHP version this project requires on your OS, then it will work no matter what. PHP 5.3 is probably enough as both symfony components require just that:

https://github.com/symfony/HttpFoundation/blob/2.6/composer.json
https://github.com/symfony/EventDispatcher/blob/2.6/composer.json

unblockvideos.com site runs php-proxy with PHP 5.3.3-7.
