### ISSUE TITLE
"symfony/event-dispatcher": "~2.6" issue with Symfony3

### ISSUE THREAD

**Issue by jakenoble** [Athlon1600/php-proxy#56]
I am trying to add this to a Symfony 3 project, but it fails due the event dispatcher dep with this error

> Problem 1
>     - Installation request for athlon1600/php-proxy ^5.0 -> satisfiable by athlon1600/php-proxy[v5.0.1].
>     - Conclusion: remove symfony/event-dispatcher v3.2.6
>     - Conclusion: don't install symfony/event-dispatcher v3.2.6
>     - athlon1600/php-proxy v5.0.1 requires symfony/event-dispatcher ~2.6 -> satisfiable by symfony/event-dispatcher[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].

Are there any workarounds? Or plans to upgrade this requirement?

**Comment by Athlon1600** [comment]
Fixed: https://github.com/Athlon1600/php-proxy/commit/dcbdf91eea4ecd315df5c856691a47c92d8219e0
