### ISSUE TITLE
event-dispatcher has removed Event::getName()

### ISSUE THREAD

**Issue by acz13** [Athlon1600/php-proxy#60]
>The methods Event::setDispatcher(), Event::getDispatcher(), Event::setName() and Event::getName() have been removed. The event dispatcher and the event name are passed to the listener call.

Causes error like

`Fatal error: Call to undefined method Proxy\Event\ProxyEvent::getName() in /home/acz13/php-proxy-app/vendor/athlon1600/php-proxy/src/Plugin/AbstractPlugin.php on line 47`

**Comment by Athlon1600** [comment]
Fixed:  
https://github.com/Athlon1600/php-proxy/commit/12584d6892779c719d26f79bf464e7d9a2b48f88
