### ISSUE TITLE
Can't Open YouTube

### ISSUE THREAD

**Issue by ahmethakanbesel** [Athlon1600/php-proxy#78]
If I try open youtube I am getting white screen.

**Comment by Athlon1600** [comment]
This has already been fixed. You need to update your php-proxy-plugin-bundle package via "composer update" or manually:  

https://github.com/Athlon1600/php-proxy-plugin-bundle/commit/b09920be6759728088893ed402545b1b57b65863

**Comment by ahmethakanbesel** [comment]
I updated YouTube plugin and I uploaded to my hosting but I'm getting "Couldn't resolve host" error all time.

**Comment by Athlon1600** [comment]
Link me to your proxy site

**Comment by ahmethakanbesel** [comment]
http://fatihweb.ml

2017-09-24 19:04 GMT+03:00 Athlon1600 <notifications@github.com>:

**Comment by Athlon1600** [comment]
Seems to work fine for me?  
https://preview.ibb.co/kF0vok/Untitled_1.png

**Comment by ahmethakanbesel** [comment]
I am getting error on normal mode but work fine in incognito mode.
https://preview.ibb.co/fA9xjQ/hata.png

**Comment by Athlon1600** [comment]
Are you on mobile or some weird desktop browser with special addons? I literally typed that same "https://youtube.com" string into your proxy, clicked "Git" and it worked.

**Comment by ahmethakanbesel** [comment]
Thanks for help. I fixed issue.
