### ISSUE TITLE
does not work with links that don't begin with http://

### ISSUE THREAD

**Issue by bennetthaselton** [Athlon1600/php-proxy#8]
The script apparently doesn't proxy links of the form
&lt;a href="filename.html"&gt;xyz&lt;/a&gt;
or
&lt;a href="/directory/filename.html"&gt;xyz&lt;/a&gt;
so if a page contains a link in that format, the link won't be changed by the proxy (which means the link will be broken on the proxified page).  The script apparently only proxifies links which begin with http://.

Example:
1) go to https://www.php-proxy.com/test/php-proxy/ or https://unblockvideos.com/
2) enter http://peacefire.org/testpages/ as the site you want to go to
3) when that page loads, scroll to the bottom and click on "link using relative path".  The target of the link is just "1.html", and the script doesn't alter it, so on the proxied page the link points to
https://www.php-proxy.com/test/php-proxy/1.html
which of course gives 404.

[Edit: Apparently the script doesn't proxify links that do begin with http:// , either.  I thought the script was proxifying the link to http://www.google.com/ on my test page, but apparently not.  So the title of this issue is misleading but I can't change it.]

**Comment by Athlon1600** [comment]
The problem was with the HTML code on that page:

```html
<a href = "1.html">Normal page</a>
```

^ those spaces around equals sign is what's confusing all the proxify regexes who aren't expecting any spaces there. Easy fix
