### ISSUE TITLE
https://www.php-proxy.com/download/php-proxy.zip - Youtube.com Fix

### ISSUE THREAD

**Issue by tibbie123** [Athlon1600/php-proxy#81]
Hi, this download does not appear to have the youtube fix update in it. Is it possible to update? thanks

**Comment by Athlon1600** [comment]
Already been addressed here:  
https://github.com/Athlon1600/php-proxy/issues/75#issuecomment-333272068

**Comment by tibbie123** [comment]
Thank you very much - worked first time!
