### ISSUE TITLE
Video player don't working

### ISSUE THREAD

**Issue by ahmethakanbesel** [Athlon1600/php-proxy#88]
http://www.hbo.com/watch-free-episodes
In this page video palayer not working for me.
![dfsdfsdfsdf](https://user-images.githubusercontent.com/6422460/31451541-0c8d8d86-aeb5-11e7-9e9a-49047d7a8198.png)

**Comment by Athlon1600** [comment]
php-proxy is only for browser basic simple sites. More complicated sites, especially video sites, require special plugins like we have for YouTube:  
https://github.com/Athlon1600/php-proxy-plugin-bundle/tree/master/src  
 
If you want to stream HBO through a proxy, you should just use an actual proxy server:  
https://www.proxynova.com/proxy-software/
