### ISSUE TITLE
Images within srcset= are not proxified

### ISSUE THREAD

**Issue by webaddicto** [Athlon1600/php-proxy#97]
The images inside srcset= are not proxified:

`<img srcset="https://cdn.pixabay.com/photo/2017/09/22/19/05/tomato-2776735__340.jpg 1x, https://cdn.pixabay.com/photo/2017/09/22/19/05/tomato-2776735__480.jpg 2x" src="THIS_URL_IS_PROXIFIED" alt="Tomato, Pepper, Onion, Mushroom, Garlic" title="Tomato, Pepper, Onion, Mushroom">`

You can test it with:

[https://pixabay.com/](https://pixabay.com/)

**Comment by Athlon1600** [comment]
fixed:  
https://github.com/Athlon1600/php-proxy/commit/70b1b862a3150f1185f8168e1dd8c139ac55f153
